// apps/vue/css-modules/src/components/ScopedCard.vue
<script setup lang="ts">
import styles from './scoped-card.module.css'

defineProps<{
  title: string
  eyebrow: string
  points: string[]
  note?: string
  elevated?: boolean
}>()
</script>

<template>
  <section :class="[styles.card, elevated !== false && styles.elevated]">
    <p :class="styles.eyebrow">{{ eyebrow }}</p>
    <h2 :class="styles.title">{{ title }}</h2>
    <ul :class="styles.list">
      <li v-for="item in points" :key="item">{{ item }}</li>
    </ul>
    <p v-if="note" :class="styles.note">{{ note }}</p>
    <slot />
  </section>
</template>

// apps/react/css-modules/src/components/ScopedCard.tsx
import type { ReactNode } from 'react'
import styles from './scoped-card.module.css'

interface ScopedCardProps {
  title: string
  eyebrow: string
  points: string[]
  note?: string
  elevated?: boolean
  children?: ReactNode
}

export function ScopedCard({ title, eyebrow, points, note, elevated = true, children }: ScopedCardProps) {
  const cardClass = `${styles.card} ${elevated ? styles.elevated : ''}`.trim()

  return (
    <section className={cardClass}>
      <p className={styles.eyebrow}>{eyebrow}</p>
      <h2 className={styles.title}>{title}</h2>
      <ul className={styles.list}>
        {points.map(item => (
          <li key={item}>{item}</li>
        ))}
      </ul>
      {note ? <p className={styles.note}>{note}</p> : null}
      {children}
    </section>
  )
}
